export class PurchaseOrderUDF {
    private transp: string;
    private fembarque: string;
    private termNeg: string;
    private modTranp: string;
    private puertDes: string;
    private estOC: string;
    private embarc: string;
    private docTras: string;
    private fdocTras: string;
    private farribPuert: string;
    private farribAlm: string;
    private tipoEmp: string;
    private observ: string;
    private puertEmb: string;
    private transpTerr: string;
    private farriboCed: string;
    private cantCont: number;
    private cbm: string;
    private fcargaList: string;
    private tiempTrans: string;
    private fsalPuert: string;
    private tiempPuert: string;
    private tiempEntComex: number;
    private fbooking: string;
    private tiempEspBooking: number;
    private festimEmb: string;
    private frecDocFin: string;
    private emisBL: string;
    private insp: string;
    private farribCedEst: string;
    private notifBL: string;
    private liqComex: string;
    private fliq: string;
    private flibBL: string;
    private conduct: string;
    private cedulCond: number;
    private placa: string;
    private contened: string;
    private precint: string;
    private enviarDatos: string;
    private vendedor: string;

    constructor() { }
}