export class PurchaseOrderUDF {
    private transp: string;
    private fembarque: Date;
    private termNeg: string;
    private modTranp: string;
    private puertDes: string;
    private estOC: string;
    private embarc: string;
    private docTras: string;
    private fdocTras: Date;
    private farribPuert: Date;
    private farribAlm: Date;
    private tipoEmp: string;
    private observ: string;
    private puertEmb: string;
    private transpTerr: string;
    private farriboCed: Date;
    private cantCont: number;
    private cbm: string;
    private fcargaList: Date;
    private tiempTrans: string;
    private fsalPuert: Date;
    private tiempPuert: string;
    private tiempEntComex: number;
    private fbooking: Date;
    private tiempEspBooking: number;
    private festimEmb: Date;
    private frecDocFin: Date;
    private emisBL: string;
    private insp: string;
    private farribCedEst: Date;
    private notifBL: string;
    private liqComex: string;
    private fliq: Date;
    private flibBL: Date;
    private conduct: string;
    private cedulCond: number;
    private placa: string;
    private contened: string;
    private precint: string;
    private enviarDatos: string;
    private vendedor: string;

    constructor() { }
}