import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { LoginComponent } from './components/login/login.component';
import { HomeComponent } from './components/home/home.component';
import { PurchaseOrdersComponent } from './components/purchase-orders/purchase-orders.component';
import { PurchaseOrderComponent } from './components/purchase-orders/purchase-order.component';
import { SalesOrdersComponent } from './components/sales-orders/sales-orders.component';
import { OrdersSapComponent } from './components/sales-orders/orders-sap/orders-sap.component';
import { OrdersModulaComponent } from './components/sales-orders/orders-modula/orders-modula.component';
import { PickingComponent } from './components/picking/picking.component';
import { PickOrderComponent } from './components/picking/pick-order/pick-order.component';
import { PickExpressComponent } from './components/picking/pick-express/pick-express.component';
import { PackingComponent } from './components/packing/packing.component';
import { ResupplyComponent } from './components/resupply/resupply.component';
import { ReportComponent } from './components/report/report.component';
import { ReportManagerComponent } from './components/report/manager/report.manager.component';
import { StockTransferLocationComponent } from './components/stock-transfer/location-transfer/stock-transfer-location.component';
import { StockTransferWarehouseComponent } from './components/stock-transfer/warehouse-transfer/stock-transfer-warehouse.component';
import { TransferComponent } from './components/stock-transfer/transfer.component';
import { ClientIgbComponent } from './components/event-feria/client-igb/client-igb.component';
import { ClientMtzComponent } from './components/event-feria/client-mtz/client-mtz.component';
import { CheckOutComponent } from './components/packing/check-out/check-out.component';
import { ShippingComponent } from './components/shipping/shipping.component';
import { WithholdingTaxesComponent } from './components/withholding-taxes/withholding-taxes.component';
import { TicketTIComponent } from './components/ticket-TI/ticket-TI.component';
import { InventoryRandomComponent } from './components/inventory/random/inventory-Random.component';
import { InventoryComponent } from './components/inventory/inventory.component';
import { StockItemComponent } from './components/inventory/stock/stock-item.component';
import { SoulStockComponent } from './components/inventory/soul/soul-stock.component';
import { ModulaComponent } from './components/inventory/modula/modula.component';
import { ProductionLabelsComponent } from './components/inventory/production/production-labels.component';
import { StockTransferModulaComponent } from './components/stock-transfer/modula-transfer/stock-transfer-modula.component';
import { ReportComexComponent } from './components/report/comex/report.comex.component';
import { OrdersMagnumComponent } from './components/sales-orders/orders-magnum/orders-magnum.component';
import { ClientRedplasComponent } from './components/event-feria/client-redplas/client-redplas.component';
import { CollectionComponent } from './components/collection/collection.component';
import { ApproveComponent } from './components/collection/approve/approve.component';
import { AuthorizedComponent } from './components/collection/authorized/authorized.component';
import { EmployeeComponent } from './components/employee/employee.component';
import { EmployeeCustodyComponent } from './components/employee/custody/employee-custody.component';
import { EmployeeJobCertifyComponent } from './components/employee/jobcertify/jobcertify.component';
import { EmployeePaystubComponent } from './components/employee/paystub/paystub.component';
import { EmployeeVacationComponent } from './components/employee/vacation/vacation.component';
import { FidelityProgramComponent } from './components/fidelity-program/fidelity-program.component';
import { RedeemCapsComponent } from './components/fidelity-program/redeem-caps/redeem-caps.component';
import { RedeemPointsComponent } from './components/fidelity-program/redeem-points/redeem-points.component';
import { CustomerComponent } from './components/collection/customer/customer.component';
import { CustomerPnComponent } from './components/collection/customer/customer-pn.component';
import { GeoLocationComponent } from './components/geo-location/geo-location.component';
import { WalletRedplas } from './components/payments-microsite/redplas/wallet-redplas.component';
import { from } from 'rxjs/observable/from';

const appRoutes: Routes = [
  { path: '', component: LoginComponent },
  { path: 'home', component: HomeComponent },
  { path: 'purchase-orders', component: PurchaseOrdersComponent },
  { path: 'purchase-order/:docNum', component: PurchaseOrderComponent },
  { path: 'sales-orders', component: SalesOrdersComponent },
  { path: 'sales-orders/orders-modula', component: OrdersModulaComponent },
  { path: 'sales-orders/orders-sap', component: OrdersSapComponent },
  { path: 'sales-orders/orders-magnum', component: OrdersMagnumComponent },
  { path: 'picking', component: PickingComponent },
  { path: 'picking/pick-order', component: PickOrderComponent },
  { path: 'picking/pick-express', component: PickExpressComponent },
  { path: 'packing', component: PackingComponent },
  { path: 'inventory', component: InventoryComponent },
  { path: 'inventory/inventory-random', component: InventoryRandomComponent },
  { path: 'inventory/stock-item', component: StockItemComponent },
  { path: 'inventory/resupply', component: ResupplyComponent },
  { path: 'inventory/stock-soul', component: SoulStockComponent },
  { path: 'inventory/modula-stock', component: ModulaComponent },
  { path: 'inventory/production-labels', component: ProductionLabelsComponent },
  { path: 'transfer', component: TransferComponent },
  { path: 'transfer/transfer-location', component: StockTransferLocationComponent },
  { path: 'transfer/transfer-warehouse', component: StockTransferWarehouseComponent },
  { path: 'transfer/transfer-modula', component: StockTransferModulaComponent },
  { path: 'report', component: ReportComponent },
  { path: 'report/manager', component: ReportManagerComponent },
  { path: 'feria/igb', component: ClientIgbComponent },
  { path: 'feria/motozone', component: ClientMtzComponent },
  { path: 'feria/redplas', component: ClientRedplasComponent },
  { path: 'check-out', component: CheckOutComponent },
  { path: 'shipping', component: ShippingComponent },
  { path: 'withholding', component: WithholdingTaxesComponent },
  { path: 'ticket-TI', component: TicketTIComponent },
  { path: 'report/comex/tracking', component: ReportComexComponent },
  { path: 'collection', component: CollectionComponent },
  { path: 'collection/approve', component: ApproveComponent },
  { path: 'collection/authorized', component: AuthorizedComponent },
  { path: 'collection/customer', component: CustomerComponent },
  { path: 'collection/customer-pn', component: CustomerPnComponent },
  { path: 'employee', component: EmployeeComponent },
  { path: 'employee/employee-custody', component: EmployeeCustodyComponent },
  { path: 'employee/employee-jobcertify', component: EmployeeJobCertifyComponent },
  { path: 'employee/employee-paystub', component: EmployeePaystubComponent },
  { path: 'employee/employee-vacation', component: EmployeeVacationComponent },
  { path: 'program-fidelity', component: FidelityProgramComponent },
  { path: 'program-fidelity/redeem-caps', component: RedeemCapsComponent },
  { path: 'program-fidelity/redeem-points', component: RedeemPointsComponent },
  { path: 'geo-location', component: GeoLocationComponent },
  { path: 'wallet-redplas', component: WalletRedplas }
];

export const appRoutingProviders: any[] = [];
export const routing: ModuleWithProviders = RouterModule.forRoot(appRoutes);
